version: '3'

services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - crustaceo_db:/var/lib/postgresql/data
