
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8001"
    ports:
      - "8001:8001"
    command: gunicorn configuration.wsgi:application --name configuration_gunicorn --workers 1 --timeout 600 --bind 0.0.0.0:8001 --log-level=debug --log-file=-
    volumes:
      - .:/backend
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
