
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
