# Generated by Django 5.0.3 on 2024-09-15 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.CharField(max_length=100)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.sale')),
            ],
            options={
                'verbose_name': 'Product Sold',
                'verbose_name_plural': 'Products Sold',
                'db_table': 'Products-Sold',
            },
        ),
    ]
