# Generated by Django 5.0.3 on 2024-09-02 00:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from django.utils.timezone import now

def create_initial_users(apps, schema_editor):
    User = apps.get_model('user', 'User')
    ShoppingCart = apps.get_model('user', 'ShoppingCart')

    cart = ShoppingCart.objects.create(
        products={},
        length=0,
        total=0.0,
    )

    cart2 = ShoppingCart.objects.create(
        products={},
        length=0,
        total=0.0,
    )

    # Crear un usuario administrador
    admin_user = User.objects.create(
        username='dmoreno',
        first_name='Diego',
        last_name='Moreno',
        email='dmoreno@unal.edu.co',
        password=make_password('password'),
        is_superuser=True,
        is_staff=True,
        type='Administrator',
        phone='1234567890',
        address='Admin Street 123',
        birthdate='1980-01-01',
        shoopingcart=cart,
    )

    # Crear un usuario cliente
    client_user = User.objects.create(
        username='sarias',
        first_name='Sergio',
        last_name='Arias',
        email='sarias@unal.edu.co',
        password=make_password('password'),
        is_superuser=False,
        is_staff=False,
        type='Client',
        phone='0987654321',
        address='Client Street 456',
        birthdate='1990-01-01',
        shoopingcart=cart2,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.JSONField(blank=True, default=dict, null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'db_table': 'ShoppingCart',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type', models.CharField(choices=[('Administrator', 'Administrator'), ('Client', 'Client')], default='Client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('shoopingcart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shoppingcart')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),

        migrations.RunPython(create_initial_users),
    ]
