# Generated by Django 5.0.3 on 2024-09-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.JSONField(default=dict),
        ),
    ]
