# Generated by Django 5.0.3 on 2024-09-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
