# Generated by Django 5.0.3 on 2024-09-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_shoppingcart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
