# Generated by Django 5.0.3 on 2024-09-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_shoppingcart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='shoopingcart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.shoppingcart'),
            preserve_default=False,
        ),
    ]
