export const BURGUER = [
    {
        "id":1,
        "score": 4,
        "name": "Cangreburguer clásica",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": true,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":2,
        "score": 3,
        "name": "Cangreburguer especial",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": true,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":3,
        "score": 2,
        "name": "Cangreburguer de piña",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":4,
        "score": 2,
        "name": "Cangreburguer de carne",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":5,
        "score": 2,
        "name": "Cangreburguer de papa",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":6,
        "score": 2,
        "name": "Cangreburguer de fresa",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":7,
        "score": 2,
        "name": "Cangreburguer de chorizo",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":8,
        "score": 2,
        "name": "Cangreburguer de nose",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":9,
        "score": 2,
        "name": "Cangreburguer de algo",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":10,
        "score": 2,
        "name": "Cangreburguer de hola",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["mala", "estaba bien"]
    },
    {
        "id":11,
        "score": 2,
        "name": "Cangreburguer de plankton",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena", "mala", "estaba bien"]
    },
    {
        "id":12,
        "score": 2,
        "name": "Cangreburguer de universidad Nacional",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"burguers",
        "comments": ["buena", "mala", "buena"]
    },
    {
        "id":13,
        "score": 4,
        "name": "Cangreburguer hello",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": true,
        "table":"burguers",
        "comments": ["buena", "mala"]
    },
    {
        "id":14,
        "score": 3,
        "name": "Cangreburguer hola bebe que mas",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": true,
        "table":"burguers",
        "comments": ["buena", "mala", "estaba bien"]
    },
    {
        "id":15,
        "score": 4,
        "name": "Cangreburguer xd",
        "price": "25000",
        "description": " Jugosa carne de cangrejo, lechuga crujiente, queso derretido, rodajas de tomate fresco, cebolla, pepinillos, y la inconfundible salsa secreta, todo entre un pan suave y esponjoso.",
        "image": "/src/assets/imagenes/cangreburguer.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": true,
        "table":"burguers",
        "comments": ["mala", "estaba bien"]
    }
]

export const FRIES = [
    {
        "id":1,
        "name": "Papas teriyaki",
        "price": "12000",
        "description": "papas en teriyaki",
        "image": "/src/assets/imagenes/papas.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"fries"
    },
    {
        "id":2,
        "name": "Papas con salsa de tomate",
        "price": "12000",
        "description": "papas con salsa de tomate",
        "image": "/src/assets/imagenes/papas.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"fries"
    },
    {
        "id":3,
        "name": "Papas con salsa rosada",
        "price": "12000",
        "description": "papas con salsa rosada",
        "image": "/src/assets/imagenes/papas.jpg",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"fries"
    }
]

export const DRINK = [
    {
        "id":1,
        "name": "Cocacola",
        "price": "12000",
        "description": "Coca cola sabor clasico",
        "image": "/src/assets/imagenes/drink.webp",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"drinks"
    },
    {
        "id":2,
        "name": "Pepsi",
        "price": "12000",
        "description": "pepepsi",
        "image": "/src/assets/imagenes/drink.webp",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"drinks"
    },
    {
        "id":3,
        "name": "Cocacola sabor cafe",
        "price": "12000",
        "description": "Cocacola con sabor cafe",
        "image": "/src/assets/imagenes/drink.webp",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"drinks"
    },
    {
        "id":4,
        "name": "Naranja postobon",
        "price": "12000",
        "description": "postobon naranja",
        "image": "/src/assets/imagenes/drink.webp",
        "count": "",
        "created_at": "",
        "is_outstanding": false,
        "table":"drinks"
    }
]