export const BURGUER = [
  {
    id: 1,
    score: 4,
    name: "Cangreburger Clásica",
    price: 28000,
    description:
      "Carne de cangrejo jugosa, lechuga crujiente, queso derretido, tomate fresco, cebolla, pepinillos y la famosa salsa secreta, todo en un pan suave y esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: true,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 2,
    score: 3,
    name: "Cangreburger Especial del",
    price: 29000,
    description:
      "Una mezcla especial de carne de cangrejo, lechuga fresca, queso fundido, tomate, cebolla, pepinillos y la icónica salsa secreta, en un pan recién horneado.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: true,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 3,
    score: 2,
    name: "Cangreburger Tropical de Piña",
    price: 30000,
    description:
      "Innovadora combinación de carne de cangrejo con piña fresca, lechuga crujiente y queso, en un pan suave, complementada con nuestra salsa secreta.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 4,
    score: 2,
    name: "Cangreburger Carnívora",
    price: 31000,
    description:
      "Carne de cangrejo jugosa acompañada de queso fundido, lechuga crujiente y nuestra salsa secreta, todo en un pan suave y esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 5,
    score: 2,
    name: "Cangreburger Papas Fritas",
    price: 32000,
    description:
      "Deliciosa carne de cangrejo combinada con papas fritas crujientes, queso, lechuga y salsa secreta, todo en un pan tierno y esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 6,
    score: 2,
    name: "Cangreburger Frutal de Fresa",
    price: 33000,
    description:
      "Carne de cangrejo jugosa con un toque frutal de fresa, lechuga, queso y nuestra famosa salsa secreta, servida en pan suave.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 7,
    score: 2,
    name: "Cangreburger del Crustáceo con Chorizo",
    price: 34000,
    description:
      "Una deliciosa mezcla de carne de cangrejo y chorizo, acompañada de lechuga, queso, y nuestra salsa secreta en un pan esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 8,
    score: 2,
    name: "Cangreburger Misteriosa",
    price: 35000,
    description:
      "Una hamburguesa misteriosa con carne de cangrejo, lechuga, queso, y salsa secreta, en un pan suave, ¿te atreves a descubrir su sabor?",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 9,
    score: 2,
    name: "Cangreburger Creativa",
    price: 36000,
    description:
      "Combinación creativa de carne de cangrejo con ingredientes secretos, acompañada de lechuga, queso y salsa especial en pan esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 10,
    score: 2,
    name: "Cangreburger Saludable",
    price: 37000,
    description:
      "Hamburguesa saludable con carne de cangrejo, lechuga fresca, queso ligero y salsa secreta, servida en pan integral.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["mala", "estaba bien"],
  },
  {
    id: 11,
    score: 2,
    name: "Cangreburger de Plankton",
    price: 38000,
    description:
      "Una hamburguesa única con carne de cangrejo y un toque especial de plankton, acompañada de lechuga, queso y salsa secreta.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena", "mala", "estaba bien"],
  },
  {
    id: 12,
    score: 2,
    name: "Cangreburger Universitaria",
    price: 39000,
    description:
      "Hamburguesa especial para estudiantes con carne de cangrejo, lechuga, queso, tomate y nuestra salsa secreta, en un pan esponjoso.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "burguers",
    comments: ["buena", "mala", "buena"],
  },
  {
    id: 13,
    score: 4,
    name: "Cangreburger de Bienvenida",
    price: 40000,
    description:
      "Deliciosa carne de cangrejo con todos los ingredientes favoritos del Crustáceo Cascarudo, servida con nuestra salsa secreta en un pan suave.",
    image: "/src/assets/imagenes/cangreburguer.jpg",
    count: "",
    created_at: "",
    is_outstanding: true,
    table: "burguers",
    comments: ["buena", "mala"],
  },
  {
    id: 14,
    score: 3,
    name: "Cangreburger Casual",
    price: 42000,
    description:
      "Una hamburguesa relajada con carne de cangrejo, lechuga fresca, queso",
  },
];

export const FRIES = [
  {
    id: 1,
    name: "Papas teriyaki",
    price: "12000",
    description: "papas en teriyaki",
    image: "/src/assets/imagenes/papas.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "fries",
  },
  {
    id: 2,
    name: "Papas con salsa de tomate",
    price: "12000",
    description: "papas con salsa de tomate",
    image: "/src/assets/imagenes/papas.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "fries",
  },
  {
    id: 3,
    name: "Papas con salsa rosada",
    price: "12000",
    description: "papas con salsa rosada",
    image: "/src/assets/imagenes/papas.jpg",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "fries",
  },
];

export const DRINK = [
  {
    id: 1,
    name: "Cocacola",
    price: "12000",
    description: "Coca cola sabor clasico",
    image: "/src/assets/imagenes/drink.webp",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "drinks",
  },
  {
    id: 2,
    name: "Pepsi",
    price: "12000",
    description: "pepepsi",
    image: "/src/assets/imagenes/drink.webp",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "drinks",
  },
  {
    id: 3,
    name: "Cocacola sabor cafe",
    price: "12000",
    description: "Cocacola con sabor cafe",
    image: "/src/assets/imagenes/drink.webp",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "drinks",
  },
  {
    id: 4,
    name: "Naranja postobon",
    price: "12000",
    description: "postobon naranja",
    image: "/src/assets/imagenes/drink.webp",
    count: "",
    created_at: "",
    is_outstanding: false,
    table: "drinks",
  },
];
