# Generated by Django 5.0.3 on 2024-09-02 00:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


def create_initial_data(apps, schema_editor):
    Burguer = apps.get_model('product', 'Burguer')
    Drink = apps.get_model('product', 'Drink')
    Fries = apps.get_model('product', 'Fries')

    Burguer.objects.create(
        id='BUR1',
        name='Classic Burguer',
        price=8.99,
        description='A classic burger with lettuce, tomato, and cheese.',
        image=None,
        count=10,
        is_outstanding=True,
        comments=['Delicious!', 'Great value!'],
        registers=[5, 4, 4],
        score=4.3,
    )

    Burguer.objects.create(
        id='BUR2',
        name='Bacon Burguer',
        price=10.99,
        description='Juicy burger with crispy bacon, cheese, and BBQ sauce.',
        image=None,
        count=5,
        is_outstanding=False,
        comments=['Love the bacon!', 'Could use more sauce.'],
        registers=[4, 4, 3],
        score=3.7,
    )

    Drink.objects.create(
        id='DRI1',
        name='Coca-Cola',
        price=1.99,
        description='Refreshing Coca-Cola beverage.',
        image=None,
        count=50,
    )

    Drink.objects.create(
        id='DRI2',
        name='Orange Juice',
        price=2.99,
        description='Freshly squeezed orange juice.',
        image=None,
        count=20,
    )

    Fries.objects.create(
        id='FRI1',
        name='Regular Fries',
        price=2.49,
        description='Crispy golden fries.',
        image=None,
        count=30,
    )

    Fries.objects.create(
        id='FRI2',
        name='Sweet Potato Fries',
        price=2.99,
        description='Sweet potato fries with a hint of cinnamon.',
        image=None,
        count=15,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burguer',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_outstanding', models.BooleanField(default=False)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('registers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]), blank=True, default=list, size=None)),
                ('score', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Burguer',
                'verbose_name_plural': 'Burguers',
                'db_table': 'Products-Burguer',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
                'db_table': 'Products-Drink',
            },
        ),
        migrations.CreateModel(
            name='Fries',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('count', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fries',
                'verbose_name_plural': 'Fries',
                'db_table': 'Products-Fries',
            },
        ),
        migrations.RunPython(create_initial_data),
    ]
